---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  playbook: ./playbook.yml

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    verifier:
      inspec_tests:
        - test/integration/default

suites:
  - name: default

